version: '0.2'
language: en,es
words:
  - abgerufen
  - Ackerbaus
  - adipiscing
  - adipisicing
  - aliquam
  - aliquet
  - amet
  - anpassen
  - Anschließend
  - Anzeigename
  - Arbeitsbereich
  - astronomisches
  - Ausführen
  - ausgewählt
  - autolinks
  - automatisch
  - backref
  - bearbeiten
  - Beitrag
  - Beiträge
  - benannt
  - Benutzername
  - Benutzeroberfläche
  - Berechtigungen
  - Bestätigen
  - Bibliothek
  - Bildschirm
  - Blockquotes
  - bootcamp
  - Brid
  - brid
  - Browserverlauf
  - charmap
  - componentized
  - Consectetur
  - consectetur
  - Contentful
  - Cosmovisión
  - customise
  - Customising
  - daher
  - Datagran
  - Dateien
  - Datenschutz
  - defaultdict
  - deepseek
  - Deepseek
  - durchsuchen
  - Dups
  - Dysnomia
  - eine
  - Einstellungen
  - elit
  - englisch
  - Entfernen
  - erfolgreich
  - Erstellen
  - Español
  - excludesfile
  - Facilisis
  - Fehler
  - Fertig
  - fintech
  - Hochspringen
  - fnref
  - frontends
  - frontmatter
  - Fußnoten
  - geolocation
  - Göttin
  - gucharmap
  - Highcharts
  - Hochladen
  - inclusivity
  - Januar
  - Justbit
  - kcharselect
  - Kieran
  - Kuiper
  - Mapbox
  - Marcone
  - Marcone's
  - März
  - Medellín
  - Meldung
  - microfrontends
  - molestie
  - multisite
  - nach
  - Nachrichten
  - naively
  - naïvely
  - nisl
  - Nulla
  - Оbserve
  - Passwort
  - pingback
  - PINGBACK
  - pretium
  - Profilbild
  - pytest
  - Rappi
  - remarkjs
  - repost
  - reposts
  - rereference
  - römischen
  - ryanmulligan
  - Santi
  - santi020k
  - Schließen
  - Sichel
  - sindresorhus
  - Speichern
  - Sprache
  - starten
  - stilisierte
  - Strikethrough
  - subsetting
  - Subsetting
  - Suchen
  - Supabase
  - tasklists
  - Teilen
  - transfonter
  - Transfonter
  - tristique
  - Überprüfen
  - velit
  - verbinden
  - Verfügbarkeit
  - Verlauf
  - Veröffentlichen
  - volutpat
  - Vorschau
  - Warten
  - WCAG
  - wcag
  - webmention
  - Webmention
  - webmentions
  - Webmentions
  - WEBMENTION
  - Weiter
  - Zeepod
  - Zurück
ignorePaths:
  - node_modules/**
  - dist/**
  - .git/**
  - package-lock.json
  - playwright-report/**
  - test-results/**
  - public/favicon.svg
